name: Build (Auto)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'chore')"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        persist-credentials: false
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: pnpm
    - name: Install dependencies
      run: pnpm install --no-frozen-lockfile
    - name: Prepare extensions
      # Don't need to do a full fetch, that would just cause a lot of unnecessary traffic
      run: node scripts/prepare-extensions.mjs
    - name: Compile
      run: pnpm run webpack:compile
    - name: Package
      run: pnpm run electron:package:dir
